all:

  #default database connection to use (from databases.yml)
  database:
    default:        mydefault

  #doctrine attributes
  attributes:

    #let doctrine automatically create db tables? (true, false)
    create_tables:  true

    #cache container (none, sqlite)
    cache:          none

    #cache directory path
    cache_dir:      %SF_CACHE_DIR%/doctrine

    #cache time to live (integer 1+)
    cache_ttl:      100

    #cache size (integer 1+)
    cache_size:     100

    #batch size (integer 0+)
    batch_size:     5

    #collection limit (integer 1+)
    coll_limit:     5

    #global event listener
    listener:

    #primary key columns (array)
    pk_columns:

    #primary key type (increment, unique)
    pk_type:        increment

    #locking (optimistic, pessimistic)
    lockmode:       pessimistic

    #enable doctrine side validation (true, false)
    vld:            true


