<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
  public function getCreatedToday()
  {
      $today = date('Y-m-d h:i:s', strtotime(date('Y-m-d')));
      return $this->createQuery('u')
          ->where('u.created_at > ?', $today)
          ->execute();
  }
}