<?php
/*
 *  $Id$
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the LGPL. For more information, see
 * <http://www.phpdoctrine.org>.
 */

/**
 * Doctrine_I18nRelation_TestCase
 *
 * @package     Doctrine
 * @license     http://www.opensource.org/licenses/lgpl-license.php LGPL
 * @category    Object Relational Mapping
 * @link        www.phpdoctrine.org
 * @since       1.0
 * @version     $Revision$
 */
class Doctrine_Ticket_1339_TestCase extends Doctrine_UnitTestCase
{
    public function prepareTables()
    {
        $this->tables[] = 'SomeModel';
        $this->tables[] = 'SomeOtherModel';

        parent::prepareTables();
    }

    public function testPreDqlSelectListener()
    {
        try {
        	$sql = Doctrine::generateSqlFromArray(array('SomeModel','SomeOtherModel'));
            $this->pass();
        }
        catch (Exception $e) {
        	$this->fail();
        }
    }
}

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSomeModel extends Doctrine_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('some_model');
    $this->hasColumn('id', 'integer', 4, array('primary' => true, 'autoincrement' => true, 'type' => 'integer', 'length' => 4));
    $this->hasColumn('name', 'string', 31, array('notnull' => true, 'type' => 'string', 'length' => 31));
    $this->hasColumn('body', 'string', 2000, array('type' => 'string', 'length' => 2000));
    $this->hasColumn('image', 'string', 64, array('type' => 'string', 'length' => 64));
    $this->hasColumn('otype', 'integer', 1, array('type' => 'integer', 'length' => 1, 'unsigned' => true));

    $this->setSubClasses(array('SomeOtherModel' => array('otype' => 1)));
  }

  public function setUp()
  {
    $i18n0 = new Doctrine_Template_I18n(array('fields' => array(0 => 'name', 1 => 'body')));
    $this->actAs($i18n0);
  }
}

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSomeOtherModel extends SomeModel
{

}

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SomeModel extends BaseSomeModel
{

}

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SomeOtherModel extends BaseSomeOtherModel
{

}